"""add disease detection tables

Revision ID: f988861096dc
Revises: 84a37a40c5c2
Create Date: 2026-09-16 11:33:30.725888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f988861096dc'
down_revision: Union[str, Sequence[str], None] = '84a37a40c5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('detected_disease', sa.String(length=150), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('prevention', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=150), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_detections_crop_id'), 'disease_detections', ['crop_id'], unique=False)
    op.create_index(op.f('ix_disease_detections_detected_at'), 'disease_detections', ['detected_at'], unique=False)
    op.create_index(op.f('ix_disease_detections_field_id'), 'disease_detections', ['field_id'], unique=False)
    op.create_index(op.f('ix_disease_detections_id'), 'disease_detections', ['id'], unique=False)
    op.create_index(op.f('ix_disease_detections_status'), 'disease_detections', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disease_detections_status'), table_name='disease_detections')
    op.drop_index(op.f('ix_disease_detections_id'), table_name='disease_detections')
    op.drop_index(op.f('ix_disease_detections_field_id'), table_name='disease_detections')
    op.drop_index(op.f('ix_disease_detections_detected_at'), table_name='disease_detections')
    op.drop_index(op.f('ix_disease_detections_crop_id'), table_name='disease_detections')
    op.drop_table('disease_detections')
    # ### end Alembic commands ###
